/// <reference lib="webworker" />
import { precacheAndRoute } from 'workbox-precaching';

declare const self: ServiceWorkerGlobalScope;

// Precache the assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST || []);

// Listen to push events
self.addEventListener("push", (event: any) => {
  const data = event.data?.json() || {};
  const title = data.title || "Task Reminder";
  const options = {
    body: data.body || "You have a scheduled task!",
    icon: "/icon-192.png",
    badge: "/icon-192.png"
  };
  event.waitUntil(self.registration.showNotification(title, options));
});
